#!/usr/bin/env sh


USER="zerrez"
BLOCK=4096


# Recieve entropy
ssh ${USER}@brok.diku.dk "dd if=/dev/urandom bs=${BLOCK} count=1" \
    | dd of=/dev/urandom

# Send entropy
dd if=/dev/urandom bs=${BLOCK} count=1 \
    | ssh ${USER}@brok.diku.dk "dd of=/dev/urandom"
